apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana-admin-username
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana-admin-password
        metadataPolicy: None
