apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ingress-certificate-istio
  namespace: infra-network
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - grafana.karafra.net
