apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: grafana-virtual-service
spec:
  hosts:
    - grafana.karafra.net
  gateways:
    - infra-monitoring/grafana-ingress-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: infra-monitoring-grafana.infra-monitoring.svc.cluster.local
            port:
              number: 80
