apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ index .Values "mimir-distributed" "mimir" "structuredConfig" "common" "storage" "s3" "bucket_name" }}-bucket-claim
spec:
  generateBucketName: {{ index .Values "mimir-distributed" "mimir" "structuredConfig" "common" "storage" "s3" "bucket_name" }}
  storageClassName: ceph-bucket
