apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-github-oauth-external-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: github-grafana-oauth-secret
    creationPolicy: Owner

  data:
    - secretKey: CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana-oauth-client-id
        metadataPolicy: None
    - secretKey: CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: grafana-oauth-client-secret
        metadataPolicy: None
