name: homelab-monitoring
apiVersion: v2
version: 0.1.0
description: A Helm chart for deploying homelab monitoring stack
type: application
appVersion: "1.0.0"
maintainers:
  - name: KarafrOrg
    email: karafra@karafra.net
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
  - homelab
dependencies:
  - name: kube-prometheus-stack
    version: 80.8.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: thanos
    version: 17.3.1
    repository: https://charts.bitnami.com/bitnami
