apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-creds-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: loki-s3-secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: loki-s3-accesskey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  target:
    name: loki-s3-creds
    creationPolicy: Owner
