apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tempo-s3-creds
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: identities
      remoteRef:
        key: seaweedfs-s3-credentials
  target:
    name: tempo-s3-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: '{{ (fromJson .identities | where "name" "tempo" | first).accessKey }}'
        AWS_SECRET_ACCESS_KEY: '{{ (fromJson .identities | where "name" "tempo" | first).secretKey }}'
        AWS_REGION: us-east-1
