apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tempo-s3-creds
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: tempo-s3-secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: tempo-s3-accesskey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
  target:
    name: tempo-s3-creds
    creationPolicy: Owner
