kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "alloy.fullname" . }}-config
data:
  config: |
    logging {
      level  = "info"
      format = "json"
    }

    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }
      output {
        traces = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      send_batch_size = 1024
      timeout         = "5s"
      output {
        traces = [otelcol.exporter.otlp.tempo.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://tempo.infra-monitoring.svc.cluster.local:4317"
      }
    }

    pyroscope.ebpf "default" {
      forward_to = [pyroscope.write.default.receiver]
    }

    pyroscope.write "default" {
      endpoint {
        url = "http://pyrosczope.infra-monitoring.svc.cluster.local:4040"
      }
    }

    // Logs
    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "app"
      }
      rule {
        source_labels = ["__meta_kubernetes_node_name"]
        target_label  = "node"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }
    }

    loki.source.kubernetes "pod_logs" {
      targets    = discovery.relabel.pod_logs.output
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://infra-monitoring-loki-distributed-gateway.infra-monitoring.svc.cluster.local/loki/api/v1/push"
      }
    }

    // Metrics
    discovery.relabel "prometheus" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_scrape"]
        regex         = "^true$"
        action        = "keep"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_port"]
        action        = "replace"
        target_label  = "__meta_kubernetes_pod_container_port_number"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
        action        = "replace"
        target_label  = "__metrics_path__"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "app"
      }
    }

    prometheus.scrape "pod_metrics" {
      targets         = discovery.relabel.prometheus.output
      forward_to      = [prometheus.remote_write.default.receiver]
      scrape_interval = "30s"
    }

    prometheus.remote_write "default" {
      endpoint {
        url = "http://infra-monitoring-mimir-gateway.infra-monitoring.svc.cluster.local/api/prom/remote/write"
      }
    }
