kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "alloy.fullname" . }}-config
data:
  config: |
    logging {
      level  = "info"
      format = "json"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    otelcol.processor.batch "traces" {
      send_batch_size = 1024
      timeout         = "5s"

      output {
        traces = [otelcol.exporter.otlp.tempo.input]
      }
    }

    otelcol.processor.batch "metrics" {
      send_batch_size = 1024
      timeout         = "5s"

      output {
        metrics = [otelcol.exporter.prometheus.beyla.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://infra-monitoring-tempo-distributed-gateway.infra-monitoring.svc.cluster.local:4317"
        tls {
          insecure = true
        }
      }
    }

    otelcol.exporter.prometheus "beyla" {
      listen_address = "0.0.0.0"
      listen_port    = 4137
    }

    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }

      output {
        metrics = [otelcol.processor.batch.metrics.input]
        traces  = [otelcol.processor.batch.traces.input]
      }
    }

    prometheus.scrape "beyla" {
      targets = [
        {
          __address__ = "127.0.0.1:4137"
        }
      ]
      scrape_interval = "15s"
      forward_to      = [prometheus.remote_write.default.receiver]
    }

    prometheus.remote_write "default" {
      endpoint {
        url = "http://infra-monitoring-mimir-gateway.infra-monitoring.svc.cluster.local/api/v1/push"
      }
    }

    discovery.relabel "pod_profiles" {
      targets = discovery.kubernetes.pods.targets

      rule {
        action = "drop"
        regex  = "Succeeded|Failed"
        source_labels = ["__meta_kubernetes_pod_phase"]
      }

      rule {
        action       = "replace"
        replacement  = "${1}/${2}"
        source_labels = [
          "__meta_kubernetes_namespace",
          "__meta_kubernetes_pod_container_name",
        ]
        target_label = "service_name"
      }

      rule {
        action = "labelmap"
        regex  = "__meta_kubernetes_pod_label_(.+)"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_node_name"]
        target_label  = "node"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }
    }

    pyroscope.ebpf "default" {
      targets    = discovery.relabel.pod_profiles.output
      forward_to = [pyroscope.write.default.receiver]
    }

    pyroscope.write "default" {
      endpoint {
        url = "http://infra-monitoring-pyroscope.infra-monitoring.svc.cluster.local:4040"
      }
    }

    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "app"
      }

      rule {
        source_labels = ["__meta_kubernetes_node_name"]
        target_label  = "node"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }
    }

    loki.source.kubernetes "pod_logs" {
      targets    = discovery.relabel.pod_logs.output
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://infra-monitoring-loki-distributed-gateway.infra-monitoring.svc.cluster.local/loki/api/v1/push"
      }
    }
